
exports.seed = function (knex, Promise) {
  // Deletes ALL existing entries
  return knex('howtoTable').del()
    .then(function () {
      // Inserts seed entries
      return knex('howtoTable').insert([
        {
          "recipe_id": 1,
          "howto": "In a large bowl, add all ingredients and mix with a whisk until only very small lumps remain. Set batter in the fridge for one hour.,\n  Read instructions on whether your pan can be placed directly onto stove or if it needs a wire rack and do accordingly. Pre-heat each half of the waffle pans on medium-high heat until hot (about 1-2 minutes).\n .Lightly brush each pan with vegetable oil (don't use spray). Turn heat to medium (I set mine at dial at 4).,\nPour 3/4 cup of the batter into the middle of the egg waffle pan and then immediately flip pan, making sure to hold pan together tightly so it doesn't leak. Cook for 2 minutes, then flip to other side and cook for 2 minutes. The egg waffle will now require one more cook on each side. Timing may vary depending on stove, but mine needed 2 more minutes on each side. (You first waffle will like still be pale yellow and may have cooked unevenly. Like the first pancake, this is your throwaway one. The ones after should look light brown when they are finished.),\nRemove the side of the pan the finished egg waffle is clinging to, and hold it above a plate with the waffle upside down. Using a chopstick or spoon, gently loosen it from the pan, starting on the top edge, using gravity to help it release. It will start to curl as it falls off and you should be able to get it out in one piece (except for the first waffle)., \nRepeat with the remaining batter (re-greasing pans first) and then serve immediately."
        },
        {
          "recipe_id": 2,
          "howto": " In a medium saucepan, bring the soy milk to a gentle boil over Medium Low heat. Stir the milk occasionally to prevent it from sticking to the bottom of the pan and burning. Use a fine sieve to skim off any bubbles or foam from the top and discard, \nPrepare the thickener by combining the corn starch and water in a small bowl. Stir until smooth., \nIn another small bowl, measure out the GDL and set aside for now., \nOnce the soy milk comes to a gentle boil, turn off the heat., \nStir the corn starch and water mixture again. Add the GDL to the corn starch mixture and combine together. Pour the contents into a 2-quart bowl., \nWorking quickly, pour the hot soy milk into the 2-quart bowl. Stir the mixture just once. (The pudding starts to set quickly so do not over-stir.), \nSkim off any bubbles on top of the soy milk and discard., \nCover the bowl with a kitchen towel and a lid., \nLet the tofu pudding rest undisturbed for 30 minutes.,Making the Ginger Syrup, Peel the ginger skin and discard. Cut the ginger into thin pieces., \nTransfer the ginger into a small bowl. Add the white sugar and combine. Let rest for 10 minutes, \nUsing a wooden pestle, break the brown slab sugar into small pieces., \nTransfer the ginger into a medium saucepan. Using Medium heat, cook the ginger stirring continuously for 5-6 minutes. When the sugar recrystallizes, add the water and brown slab sugar. Cook over Medium heat melting the sugar. Stir occasionally to help the sugar dissolve. Once the sugar is completely dissolved, reduce the heat to Medium Low. Continue cooking for another 5-6 minutes allowing the liquid to thicken into a syrup., \nTransfer the ginger syrup into a medium bowl and let cool. "
        },
        {
          "recipe_id": 3,
          "howto": "  Wash all vegetables., \nSlice long chilies in half and remove seeds. Slice eggplant at an angle (to make the slices longer) into 1\/\4 thick slices.  , \nSlice bitter melon into 1\/\" thick rounds and remove the inside pulp and seeds, leaving only the green rind. , \nSmear the fish paste into/onto all vegetables., \nHeat up a non stick pan (we use cast iron) over medium heat, add 1 tbsp oil and add in green chilies, fish paste side down, and turn heat to low.  , \nCook for 3-4 minutes until fish paste is a golden brown, then flip and cook for another 2-3 minutes.  Check bottom, when golden brown spots appear, remove to serving plate., \nTurn heat to medium, add another tbsp of oil, then add in eggplant, fish paste side down and turn heat to low.  Cook for 4-5 minutes or until the fish paste is a golden brown, then flip and cook for another 3-4 minutes.  , \nAdd 3 tbsp of chicken stock, cover and turn heat up to medium.  When the stock boils turn down heat to low and let cook until the eggplant is cooked through. , \nRemove to serving plate.  Repeat for the bitter melon. "
        },
        {
          "recipe_id": 4,
          "howto": "  Soak the Chinese vermicelli noodles in water until soften, cut it few times. Marinate the pork/ chicken with some soy sauce, sugar and corn starch. Or you can used leftover chicken. Cut the shiitake mushrooms and black fungus into thinly slices., \nIn a large pot, bring the chicken broth into boil, then add in meat, shiitake mushrooms and black fungus. Once it boils, turn to low heat and cook for 10 minutes. Then return the heat to medium high, add in all seasoning and vermicelli noodles. Cook for 2 minutes., \nMix the water chestnut flour with 2 tablespoons of water, then add in the soup, keep stirring and soup will thicken. Remove from heat, add in beaten egg, let it set for 5 seconds, then use chopsticks to stir to make egg drop. Enjoy!!"
        },
        {
          "recipe_id": 5,
          "howto": "    Whisk first 5 ingredients in medium bowl. Set dressing aside., \nCook beans in medium saucepan of boiling salted water until crisp-tender, about 5 minutes. , \nRinse under cold water. Cut into 2-inch pieces. , \nUsing julienne peeler, peel enough papaya to measure 6 cups. Place in large bowl. , \nAdd tomatoes, cilantro, green onions, chile, and green beans. Pour dressing over; toss. , \nSprinkle peanuts over and serve."
        },
        {
          "recipe_id": 6,
          "howto": "METHOD -FOR PASTRY, Cream butter with icing sugar, egg yolk and egg white., \nAdd in flour and mix well. Once it is well mixed, using hand, press the mixture together and form a dough. If the dough is too wet or oily, do add some flour. Give it a few knead. , \nWrap the dough in a clingwrap. Put it into the fridge for 15mins to let it cool. Take the dough out of the fridge., \nCut pastries into 12 equal portion (about 38g each). Roll individual dough into a ball. , \nUsing a tart case, press the pastry ball into a flat piece. Line dough in the middle of tart cases, lightly press the dough into the tart cases.  \nRefrigerate the tart cases for 30mins, and it is ready to use.,METHOD -FOR FILLING , Add castor sugar into hot water, mix until sugar completely dissolved. , \nSet aside and let it cool. Beat eggs with milk, vanilla essence and salt. Pour in sugar water. Mix well, \nSift egg mixture TWICE to achieve smooth egg mixture. , \nTake tarts out of the refrigerator, carefully pour egg mixture into each tart shells. Bake tarts for 25mins at 180 degree, fan ON."
        },
        {
          "recipe_id": 7,
          "howto": "In a bowl wash rice well in several changes of cold water until water is clear. Soak rice in cold water to cover overnight., \n Drain rice well in a sieve. Set sieve over a large deep saucepan of simmering water (sieve should not touch water) and steam rice, covered with a kitchen towel and a lid, 30 to 40 minutes, or until tender (check water level in pan occasionally, adding more water if necessary)., \n While rice is cooking, in a small saucepan bring 1 cup coconut milk to a boil with 1/3 cup sugar and salt, stirring until sugar is dissolved, and remove from heat. Keep mixture warm., \n Transfer cooked rice to a bowl and stir in coconut-milk mixture. Let rice stand, covered, 30 minutes, or until coconut-milk mixture is absorbed. Rice may be prepared up to this point 2 hours ahead and kept covered at room temperature, \n While rice is standing, in cleaned small pan slowly boil remaining 1/3 cup coconut milk with remaining 3 tablespoons sugar, stirring occasionally, 1 minute. Transfer sauce to a small bowl and chill until cool and thickened slightly., \n To serve, mold 1/4 cup servings of sticky rice on dessert plates. Drizzle desserts with sauce and sprinkle with sesame seeds. Divide mango slices among plates."
        },
        {
          "recipe_id": 8,
          "howto": "In a blender or mortar, blend or pound garlic, salt, peanuts, chilies, sugar and shrimp (if using) into a paste. Transfer to a large bowl and mix in lime juice and fish sauce. Use a spoon (or the mortar) to lightly crush tomatoes and beans (if using), then add to bowl and mix lightly. \nPeel and coarsely grate or shred papaya, discarding seeds and inner membrane. There should be 4 to 6 cups., \nAdd papaya to bowl and lightly but thoroughly toss together. Taste for seasoning. Mound in a bowl (if desired, line bowl with lettuce leaves beforehand). Sprinkle with peanuts and serve."
        },
        {
          "recipe_id": 9,
          "howto": "Preheat steamer and greasing pudding cups with oil. Place cups into steamer., \n In a pot over medium high heat, melt sugar and water together. Set aside., \n Combine rice flour, wheat starch and coconut milk into a smooth paste, \n Slowly whisk in sugar mixture., \n Put mixture into a spouted cup for easy pouring. After steamer is heated for 2-3 minutes, pour mixture into the preheated pudding cups., \n Add in beans., \n Steam for 15-20 minutes., \n Let pudding cakes cool for about 2 hours before serving."
        },
        {
          "recipe_id": 10,
          "howto": "Heat 1 tbsp oil in a very large heavy based skillet or wok over high heat, \nAdd garlic, cook 15 seconds. Add chicken, cook until it mostly changes from pink to white., \nAdd Chinese broccoli stems, cook until chicken is almost cooked through., \nAdd Chinese broccoli leaves, cook until just wilted., \nPush everything to one side, crack egg in and scramble. Remove everything onto a plate (scrape wok clean)., \nReturn wok to stove, heat 2 tbsp oil over high heat.  \nAdd noodles and Sauce. Toss as few times as possible to disperse Sauce and make edges of noodles caramelise. , \nQuickly add chicken and veg back in, and toss to disperse. Serve immediately!"
        },
        {
          "recipe_id": 11,
          "howto": "Pour vegetable or mushroom stock into a large saucepan. Add in minced garlic, freshly grated ginger, soy sauce, rice wine vinegar, and miso if using. Bring the broth to a boil and reduce to a simmer., \nAdd in sliced mushrooms, red pepper, and bok choy into broth, and simmer for 7-10 minutes, or until greens are wilted., \nAdd in packaged ramen noodles (discard seasoning pack) and cook according to package directions‚Äìabout 3 minutes., \nDish up cooked ramen into serving bowls and top ramen as desired. "
        },
        {
          "recipe_id": 12,
          "howto": "Prepare sago pearls. Put a small pot of water to boil. Once boiling, add the sago seeds. Lower heat and cook for around 10 minutes. Turn off the heat and allow the remaining heat to finish cooking the sago seeds. When the sago seeds turn translucent, ladle up and place them in a bowl of water till ready to use., \nCut the pomelo. Slice off the top of the pomelo. Make vertical slits (about ¬Ω inch thick) along the sides of the pomelo. Using your hand, peel off the skin working from the top to bottom. Peel away the membrane from 3 wedges of pomelo and remove the pomelo sacs. Loosen the sacs with a spoon and set aside., \nCut the mango into cubes. Reserve about a quarter of the mangoes and set aside to be used as toppings for the dessert., \nPlace the mango cubes, evaporated milk and ice cubes into a blender. Blend for a short while till smooth. I did not break the ice completely as I wanted some pieces of ice cubes inside the dessert. You may replace the ice cubes with water if you wish to chill it in the fridge., \nPour pureed mango into a large bowl. Strain cooked sago seeds with a small sieve and add into the mango puree. Add the pomelo sacs and 3 tbsp of sugar syrup (or to taste). Reserve some of the pomelo sacs for topping. Mix well., \nRation into serving bowls and top with reserved mango cubes and pomelo sacs. Serve immediately or refrigerate to chill and serve later."
        },
        {
          "recipe_id": 13,
          "howto": "Gather the ingredients. , \n Combine water and tea leaves in a small saucepan over medium heat., \n Bring to a low boil. Reduce heat and simmer for 3 minutes., \n Remove from heat. Stir in sweetened, condensed milk. Return to heat., \n Return to a boil. Simmer for 3 more minutes., \n Strain tea and condensed milk., \n Serve hot or (optional) chill and serve over ice. Small glasses are ideal."
        },
        {
          "recipe_id": 14,
          "howto": "Heat oil in a wok or large pan over medium heat. Add pork shank, and turn up the heat a bit. Fry until golden brown on both sides. Transfer the leg to drain on a paper towel., \nPound garlic, peppercorns, and corriander in a mortar and pestle until it becomes a fine paste. Set aside., \nPlace fried pig leg in a pot and cover with water. Add garlic paste mixture, cinnamon, star anise, black soy, thin soy, Golden Mtn, salt, palm sugar, 5-spice, and eggs. Bring to a boil then reduce heat, and cook for another 2-3 hours until tender., \nWhile the pork is cooking, thinly slice the pickled mustard green, gently squeeze it to remove the pickling liquid, and rinse it one time in a colander. Then slowly boil it in a bit of water or chicken stock, about  5 cups, until water evaporates, and set aside., \nSeparately, pound 2-3 fresh Thai chile peppers in a mortar and pestle. Transfer to a small sauce bowl, add 1 teaspoon salt and 1/2 cup vinegar. This sauce should be served with the khao kha moo., \nServe the meat over steamed jasmine rice, topped with some pickled mustard green, steamed bokchoy and the chile-vinegar sauce."
        },
        {
          "recipe_id": 15,
          "howto": "Heat oil in a wok or large pan over medium heat. Add pork shank, and turn up the heat a bit. Fry until golden brown on both sides. Transfer the leg to drain on a paper towel., \nPound garlic, peppercorns, and corriander in a mortar and pestle until it becomes a fine paste. Set aside., \nPlace fried pig leg in a pot and cover with water. Add garlic paste mixture, cinnamon, star anise, black soy, thin soy, Golden Mtn, salt, palm sugar, 5-spice, and eggs. Bring to a boil then reduce heat, and cook for another 2-3 hours until tender., \nWhile the pork is cooking, thinly slice the pickled mustard green, gently squeeze it to remove the pickling liquid, and rinse it one time in a colander. Then slowly boil it in a bit of water or chicken stock, about  5 cups, until water evaporates, and set aside., \nSeparately, pound 2-3 fresh Thai chile peppers in a mortar and pestle. Transfer to a small sauce bowl, add 1 teaspoon salt and 1/2 cup vinegar. This sauce should be served with the khao kha moo., \nServe the meat over steamed jasmine rice, topped with some pickled mustard green, steamed bokchoy and the chile-vinegar sauce."
        },
        {
          "recipe_id": 16,
          "howto": "Heat oil in a wok or large pan over medium heat. Add pork shank, and turn up the heat a bit. Fry until golden brown on both sides. Transfer the leg to drain on a paper towel., \nPound garlic, peppercorns, and corriander in a mortar and pestle until it becomes a fine paste. Set aside., \nPlace fried pig leg in a pot and cover with water. Add garlic paste mixture, cinnamon, star anise, black soy, thin soy, Golden Mtn, salt, palm sugar, 5-spice, and eggs. Bring to a boil then reduce heat, and cook for another 2-3 hours until tender., \nWhile the pork is cooking, thinly slice the pickled mustard green, gently squeeze it to remove the pickling liquid, and rinse it one time in a colander. Then slowly boil it in a bit of water or chicken stock, about  5 cups, until water evaporates, and set aside., \nSeparately, pound 2-3 fresh Thai chile peppers in a mortar and pestle. Transfer to a small sauce bowl, add 1 teaspoon salt and 1/2 cup vinegar. This sauce should be served with the khao kha moo., \nServe the meat over steamed jasmine rice, topped with some pickled mustard green, steamed bokchoy and the chile-vinegar sauce."
        },
        {
          "recipe_id": 17,
          "howto": "Heat oil in a wok or large pan over medium heat. Add pork shank, and turn up the heat a bit. Fry until golden brown on both sides. Transfer the leg to drain on a paper towel., \nPound garlic, peppercorns, and corriander in a mortar and pestle until it becomes a fine paste. Set aside., \nPlace fried pig leg in a pot and cover with water. Add garlic paste mixture, cinnamon, star anise, black soy, thin soy, Golden Mtn, salt, palm sugar, 5-spice, and eggs. Bring to a boil then reduce heat, and cook for another 2-3 hours until tender., \nWhile the pork is cooking, thinly slice the pickled mustard green, gently squeeze it to remove the pickling liquid, and rinse it one time in a colander. Then slowly boil it in a bit of water or chicken stock, about  5 cups, until water evaporates, and set aside., \nSeparately, pound 2-3 fresh Thai chile peppers in a mortar and pestle. Transfer to a small sauce bowl, add 1 teaspoon salt and 1/2 cup vinegar. This sauce should be served with the khao kha moo., \nServe the meat over steamed jasmine rice, topped with some pickled mustard green, steamed bokchoy and the chile-vinegar sauce."
        },
        {
          "recipe_id": 18,
          "howto": "Heat oil in a wok or large pan over medium heat. Add pork shank, and turn up the heat a bit. Fry until golden brown on both sides. Transfer the leg to drain on a paper towel., \nPound garlic, peppercorns, and corriander in a mortar and pestle until it becomes a fine paste. Set aside., \nPlace fried pig leg in a pot and cover with water. Add garlic paste mixture, cinnamon, star anise, black soy, thin soy, Golden Mtn, salt, palm sugar, 5-spice, and eggs. Bring to a boil then reduce heat, and cook for another 2-3 hours until tender., \nWhile the pork is cooking, thinly slice the pickled mustard green, gently squeeze it to remove the pickling liquid, and rinse it one time in a colander. Then slowly boil it in a bit of water or chicken stock, about  5 cups, until water evaporates, and set aside., \nSeparately, pound 2-3 fresh Thai chile peppers in a mortar and pestle. Transfer to a small sauce bowl, add 1 teaspoon salt and 1/2 cup vinegar. This sauce should be served with the khao kha moo., \nServe the meat over steamed jasmine rice, topped with some pickled mustard green, steamed bokchoy and the chile-vinegar sauce."
        },
      ]);
    });
};
